songList = {
    # Core (1992)
    "Dead & Bloated": None,
    "Sex Type Thing": None,
    "Wicked Garden": None,
    "No Memory": None,
    "Sin": None,
    "Creep": None,
    "Plush": None,
    "Piece of Pie": None,
    "Crackerman": None,
    "Where the River Goes": None,
    "Silvergun Superman": None,
    "Bellyaching": None,
    "Naked Sunday": None,

    # Purple (1994)
    "Meatplow": None,
    "Vasoline": None,
    "Lounge Fly": None,
    "Interstate Love Song": None,
    "Still Remains": None,
    "Pretty Penny": None,
    "Silvergun Superman": None,
    "Big Empty": None,
    "Unglued": None,
    "Army Ants": None,
    "Kitchenware & Candybars": None,

    # Tiny Music... Songs from the Vatican Gift Shop (1996)
    "Press Play": None,
    "Pop's Love Suicide": None,
    "Tumble in the Rough": None,
    "Big Bang Baby": None,
    "Lady Picture Show": None,
    "And So I Know": None,
    "Trippin' on a Hole in a Paper Heart": None,
    "Art School Girl": None,
    "Adhesive": None,
    "Ride the Cliché": None,
    "Daisy": None,
    "Seven Caged Tigers": None,

    # No. 4 (1999)
    "Down": None,
    "Heaven & Hot Rods": None,
    "Pruno": None,
    "Church on Tuesday": None,
    "Sour Girl": None,
    "No Way Out": None,
    "Atlanta": None,
    "Quick Fix": None,
    "Rhino": None,
    "Too Cool Queenie": None,
    "Tumble in the Rough": None,

    # Shangri-La Dee Da (2001)
    "Dumb Love": None,
    "Days of the Week": None,
    "Coma": None,
    "Hollywood Bitch": None,
    "Fantastic Voyage": None,
    "Regeneration": None,
    "Bi-Polar Bear": None,
    "Transmissions from a Distant Star": None,
    "A Song for Sleeping": None,
    "Hello, It's Late": None,
    "Long Way Home": None,

    # Stone Temple Pilots (2010)
    "Between the Lines": None,
    "Take a Load Off": None,
    "Huckleberry Crumble": None,
    "Hickory Dichotomy": None,
    "Dare If You Dare": None,
    "Cinnamon": None,
    "Hazy Daze": None,
    "Bagman": None,
    "Peacoat": None,
    "Fast as I Can": None,
    "First Kiss on Mars": None,
    "Maver": None,

    # High Rise (2013 EP with Chester Bennington)
    "Out of Time": None,
    "Black Heart": None,
    "Paralyzed": None,
    "Tomorrow": None,
    "Cry Cry": None,

    # Stone Temple Pilots (2018)
    "Roll Me Under": None,
    "Never Enough": None,
    "The Art of Letting Go": None,
    "Finest Hour": None,
    "Good Shoes": None,
    "Reds & Blues": None,
    "Gypsy Biker": None,
    "Meadow": None,
    "Thought She'd Be Mine": None,
    "Train": None,
    "The Autumn Song": None,

    # Perdida (2020)
    "Fare Thee Well": None,
    "Three Wishes": None,
    "Perdida": None,
    "Years": None,
    "She's My Queen": None,
    "Miles Away": None,
    "You Found Yourself While Losing Your Mind": None,
    "I Didn't Know the Time": None,
    "Last Child": None,
    "Regeneration": None
}